batch_size: 8
checkpoints_dir: ./checkpoints
data_dir: ./data
data_dir_2d: ./data2d
datasets:
- params:
    kaggle_path: andrewmvd/covid19-ct-scans
    loader_name: TIFFLoader
    image_key: ct_scan
    mask_key: infection_mask
    name: covid19-ct-scans
    type: 2d
  type: KaggleDataset
kaggle_api_key: null
kaggle_username: null
logs_dir: ./logs
max_epochs: 10
n_trials: 1
name: learning_rate_search
num_workers: 2
params:
  img_size: [512, 512]
  hidden_dim:
    high: 64
    log: true
    low: 64
    name: hidden_dim
  learning_rate:
    high: 0.001
    log: true
    low: 0.0001
    name: learning_rate
  loss_type:
    choices:
    - DiceLoss
    - TverskyLoss
    name: loss_type
  lr_decay:
    high: 0.1
    log: true
    low: 1.0e-05
    name: lr_decay
  model_type: unet2d
  optim_type:
    choices:
    - Adam
    name: optim_type
  weight_decay:
    high: 0.1
    log: true
    low: 1.0e-05
    name: weight_decay
random_state: 42
test_size: 0.1
threshold: 0.5

